language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  include:
    # test 2.3 LTS
    - php: 5.3
      env: SYMFONY_VERSION=2.3.*
    # test 2.7 LTS
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    # test 2.8 LTS
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    # test the latest stable 3.x release
    - php: 5.6
      env: SYMFONY_VERSION=^3.0
    # test the latest release (including beta releases)
    - php: 7.1
      env: DEPENDENCIES=beta

before_script:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit
